name: bIRCh
main: me.heldplayer.bIRCh.bIRCh
version: 0.1
author: heldplayer
description: A program for relaying IRC to minecraft servers
commands:
  irc:
    description: Main plugin command
    usage: /<command> help
    permission: birch.command
permissions:
  birch.command:
    default: op
    description: Allows you to use the /irc command